export const action_type = {
  
  SEND_MESSAGE: 'SEND_MESSAGE',
  UPDATE_NEW_MESSAGE_TEXT: 'UPDATE_NEW_MESSAGE_TEXT',
  ADD_POST: 'ADD_POST',
  UPDATE_NEW_POST_TEXT: 'UPDATE_NEW_POST_TEXT',
  FOLLOW: 'FOLLOW',
  UNFOLLOW: 'UNFOLLOW',
  SET_USERS: 'SET_USERS'

}